version: "3"

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "payhere"
    container_name: "mysql"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
