version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: "payhere-mysql"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    container_name: "payhere-web"
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: payhere-mysql
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
